from typing import Protocol
from app.domain_models.deck import Deck


class DeckRepoProtocol(Protocol):
    def get_all_by_user(self, user_id: int) -> list[Deck]: ...

    def get_main_by_user(self, user_id: int) -> Deck | None: ...

    def get_by_id(self, deck_id: int) -> Deck | None: ...

    def create(self, user_id: int, name: str, deck_content: str) -> Deck: ...

    def update(self, deck_id: int, name: str | None = None, deck_content: str | None = None) -> Deck | None: ...

    def set_main(self, user_id: int, deck_id: int) -> Deck | None: ...

    def delete(self, deck_id: int) -> bool: ...
