from typing import Protocol
from app.domain_models.friends import Friends
from app.domain_models.user import User

class FriendsRepoProtocol(Protocol):

    def create_friend_request(self, user: User, friend: User, status: str) -> Friends: ...

    def update_friend_request(self, friendship: Friends) -> Friends: ...

    def get_friend_request(self, sender_id: int, receiver_id: int) -> Friends | None: ...

    def get_friendships(self, user_id: int) -> list[Friends]: ...

    def delete_friendship(self, friendship: Friends) -> bool: ...

    def get_user_by_friend_code(self, friend_code: str) -> User | None: ...

    def cleanup_rejected_requests(self) -> int: ...