from typing import Protocol, Optional, BinaryIO


class ImageStorageProtocol(Protocol):
    def save_image(self, key: str, image_data: BinaryIO) -> str: ...

    def delete_image(self, key: str) -> None: ...

    def get_image(self, key: str): ...
