from typing import Protocol


class ImageRepoProtocol(Protocol):
    def save_user_image(self, key: str, user_id) -> str: ...

    def get_card_key_by_id(self, image_id: int) -> str: ...

    def get_card_keys_by_user_id(self, user_id: int) -> list[str]: ...

    def get_user_key_by_id(self, user_id: int) -> str: ...

    def has_profile_picture(self, user_id: int) -> bool: ...
