"""Make_defender_id_nullable

Revision ID: 0982039f31fa
Revises: 64698f0e5a80
Create Date: 2026-07-13 21:51:42.303080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0982039f31fa'
down_revision = '64698f0e5a80'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'what_beats_rock' in tables:
        with op.batch_alter_table('what_beats_rock', schema=None) as batch_op:
            batch_op.alter_column('defender_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('what_beats_rock', schema=None) as batch_op:
        batch_op.alter_column('defender_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
