"""Add highscore to WBRModel

Revision ID: 1f1a61e99cb8
Revises: d60642186547
Create Date: 2026-07-13 23:44:12.036909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1a61e99cb8'
down_revision = 'd60642186547'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'what_beats_rock' in tables:
        columns = [c['name'] for c in inspector.get_columns('what_beats_rock')]
        if 'highscore' not in columns:
            with op.batch_alter_table('what_beats_rock', schema=None) as batch_op:
                batch_op.add_column(sa.Column('highscore', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('what_beats_rock', schema=None) as batch_op:
        batch_op.drop_column('highscore')

    # ### end Alembic commands ###
