"""lobby name

Revision ID: 2b48307142dd
Revises: 194c86540cac
Create Date: 2026-07-30 03:20:56.504522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b48307142dd'
down_revision = '194c86540cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_battle_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_battle_game', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
