"""added main deck

Revision ID: 2ebb37b0dbbe
Revises: 2b48307142dd
Create Date: 2026-07-30 06:30:39.045975

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ebb37b0dbbe'
down_revision = '2b48307142dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('is_main', sa.Boolean(), nullable=False, server_default=sa.false()))


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###
