"""card stats addition

Revision ID: 47551b4cb780
Revises: 1f1a61e99cb8
Create Date: 2026-07-29 22:24:13.028928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47551b4cb780'
down_revision = '1f1a61e99cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'battle_type',
                sa.String(),
                nullable=False,
                server_default='fighter'
            )
        )
        batch_op.add_column(
            sa.Column(
                'attack',
                sa.Integer(),
                nullable=False,
                server_default='10'
            )
        )
        batch_op.add_column(
            sa.Column(
                'health',
                sa.Integer(),
                nullable=False,
                server_default='10'
            )
        )
        batch_op.add_column(
            sa.Column(
                'cost',
                sa.Integer(),
                nullable=False,
                server_default='1'
            )
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('health')
        batch_op.drop_column('attack')
        batch_op.drop_column('battle_type')

    # ### end Alembic commands ###
