"""Add history to WBRModel

Revision ID: d60642186547
Revises: 0982039f31fa
Create Date: 2026-07-13 22:04:04.280587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60642186547'
down_revision = '0982039f31fa'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'what_beats_rock' in tables:
        columns = [c['name'] for c in inspector.get_columns('what_beats_rock')]
        if 'history' not in columns:
            with op.batch_alter_table('what_beats_rock', schema=None) as batch_op:
                batch_op.add_column(sa.Column('history', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('what_beats_rock', schema=None) as batch_op:
        batch_op.drop_column('history')

    # ### end Alembic commands ###
